#!/usr/bin/env bash
# Removes portfolio-only source files that are unreachable from the Vedin entry
# (main.tsx). Generated after verifying `tsc` + `vite build` pass without them.
# Run from the repo root:  bash scripts/cleanup-portfolio.sh
set -e
cd "$(dirname "$0")/.."

git rm -f "src/App.tsx"
git rm -f "src/components/AILineBot.tsx"
git rm -f "src/components/About.tsx"
git rm -f "src/components/AboutMe.tsx"
git rm -f "src/components/AdminPoetryManager.tsx"
git rm -f "src/components/AgentFlow.tsx"
git rm -f "src/components/AlgorithmLab.tsx"
git rm -f "src/components/AntimatterSim.tsx"
git rm -f "src/components/ArticleCard.tsx"
git rm -f "src/components/ArticlesSection.tsx"
git rm -f "src/components/Bibliography.tsx"
git rm -f "src/components/BlogSnippets.tsx"
git rm -f "src/components/BootScreen.tsx"
git rm -f "src/components/CRTHero.tsx"
git rm -f "src/components/CyberCursor.tsx"
git rm -f "src/components/CyberPoetry.tsx"
git rm -f "src/components/DeferUntilVisible.tsx"
git rm -f "src/components/Exploring.tsx"
git rm -f "src/components/FarewellRSVP.tsx"
git rm -f "src/components/GalleryPage.tsx"
git rm -f "src/components/GallerySection.tsx"
git rm -f "src/components/Gateway.tsx"
git rm -f "src/components/GitHubProjects.tsx"
git rm -f "src/components/HudFrame.tsx"
git rm -f "src/components/JourneyCrosslink.tsx"
git rm -f "src/components/JourneyHubNav.tsx"
git rm -f "src/components/Lightbox.tsx"
git rm -f "src/components/LiveCodeShowcase.tsx"
git rm -f "src/components/MarqueeGallery.tsx"
git rm -f "src/components/MediaGallery.tsx"
git rm -f "src/components/MegaFooter.tsx"
git rm -f "src/components/Navbar.tsx"
git rm -f "src/components/PageShell.tsx"
git rm -f "src/components/Philosophy.tsx"
git rm -f "src/components/Projects.tsx"
git rm -f "src/components/ProjectsSection.tsx"
git rm -f "src/components/PythonAutomation.tsx"
git rm -f "src/components/QuantumLab.tsx"
git rm -f "src/components/Sanctuary.tsx"
git rm -f "src/components/SanctuaryAdmin.tsx"
git rm -f "src/components/SeasonalGallery.tsx"
git rm -f "src/components/SectionSkeleton.tsx"
git rm -f "src/components/StudyingLibrary.tsx"
git rm -f "src/components/TechDecor.tsx"
git rm -f "src/components/TechStack.tsx"
git rm -f "src/components/TravelChronicles.tsx"
git rm -f "src/components/VideoShowcase.tsx"
git rm -f "src/components/VisitorGlobe.tsx"
git rm -f "src/config/assets.ts"
git rm -f "src/data/content.js"
git rm -f "src/data/footerData.js"
git rm -f "src/data/galleryData.js"
git rm -f "src/data/journeyHub.ts"
git rm -f "src/hooks/useCyberReveal.js"
git rm -f "src/hooks/useGallery.ts"
git rm -f "src/hooks/useInView.ts"
git rm -f "src/hooks/useIsMobile.ts"
git rm -f "src/lib/cyberScroll.js"
git rm -f "src/lib/portfolioApi.ts"
git rm -f "src/lib/sanctuaryParticles.js"
git rm -f "src/lib/sceneImage.js"
git rm -f "src/types/api.ts"

echo "Removed 62 portfolio files. Now run: npm run build"
